### ISSUE TITLE
Some exception in reader.py 

### ISSUE THREAD

**Issue by 3wh1te** [Thijsvanede/FlowPrint#8]
**Describe the bug**
In function read_pyshark
```
def read_pyshark(self, path):
     pcap = iter(pcap_obj)
.....
     pcap.close()
```
pcap doesn't have the close() function. It rasies a exception **RuntimeError: Event loop is closed**
```

Exception ignored in: <bound method Capture.__del__ of <FileCapture android\appinventor.ai_reflectiveapps.rbxlook.pcap>>
Traceback (most recent call last):
  File "xxx\lib\site-packages\pyshark\capture\capture.py", line 435, in __del__
    self.close()
  File "xxx\site-packages\pyshark\capture\capture.py", line 426, in close
    self.eventloop.run_until_complete(self.close_async())
  File "xxx\lib\asyncio\base_events.py", line 443, in run_until_complete
    self._check_closed()
  File "xxx\lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
\fingerprint.py:159: RuntimeWarning: coroutine 'Capture.close_async' was never awaited
  return hash(frozenset([x for x in self]))

```
 
So I changed it like that
```
def read_pyshark(self, path):
     pcap_obj = pyshark.FileCapture(path)
     pcap = iter(pcap_obj)
.....
     pcap_obj.close()
```
 and it worked!

**Comment by Thijsvanede** [comment]
You are completely correct, thank you very much for notifying me.
I have pushed your bugfix, this is now on the latest GitHub and pip versions of FlowPrint.
I also added you to the special thanks section for contributors of this project, i'ts still building but it should be available soon at: [https://flowprint.readthedocs.io/en/latest/contributors.html](https://flowprint.readthedocs.io/en/latest/contributors.html).
